### ISSUE TITLE
this issue is coming when i am trying to run the code 

### ISSUE THREAD

**Issue by TheTurboSlayer** [CodeWithHarry/TextUtils-React#42]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (D:\Desktop\TextUtils-React\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Desktop\TextUtils-React\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\Desktop\TextUtils-React\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\Desktop\TextUtils-React\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\Desktop\TextUtils-React\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\Desktop\TextUtils-React\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\Desktop\TextUtils-React\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Desktop\TextUtils-React\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by ShahMuhaymin** [comment]
facing same error

**Comment by TheTurboSlayer** [comment]
Did you get any way to correct it?

Shorya Goel

**Comment by susmitasanti** [comment]
To resolve the OpenSSL issue with Node.js, please follow these steps:

### For Windows Command Prompt:
1. Open Command Prompt and navigate to your project directory.
   
2. Set the `NODE_OPTIONS` environment variable:
   ```cmd
   set NODE_OPTIONS=--openssl-legacy-provider

### For Linux, macOS Command Prompt:
1. Open Command Prompt and navigate to your project directory.
   
2. Set the `NODE_OPTIONS` environment variable:
   ```cmd
   export NODE_OPTIONS=--openssl-legacy-provider

### Start your app
 ```cmd
   npm run start
